⬆ Upgrade GraalVM to 20.3.0
First upgrade attempt made native image fail:

	Error: Class initialization of sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher failed. Use the option --initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher to explicitly request delayed initialization of this class.

A build configuration has been added to make native image build succeed.
Image generation now succeeds (with many warnings ⚠️) and its execution works on my machine! ©️

Configuration have been generated this way:

	java -agentlib:native-image-agent=config-output-dir=conf -cp ./target/uberjar/strava-activity-graphs-0.1.0-SNAPSHOT-standalone.jar strava_activity_graphs/core$_main f062b70668948263b1e21287ed0cb554217902c7 >/dev/null

See documention on build configuration:
https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#specifying-configuration-files-as-native-image-arguments